"""
Flask-Fixtures
--------------

A fixtures library for testing Flask apps.
"""

import os
import subprocess
from setuptools import setup


root_dir = os.path.abspath(os.path.dirname(__file__))
package_dir = os.path.join(root_dir, 'flask_fixtures')


# Fetch version from git tags, and write to version.py (http://bit.ly/1gImR86)
version_py = os.path.join(package_dir, 'version.py')

# Try to get the current version from git and fallback onto the version in
# version.py if for some reason we can't read it from git.
try:
    stdoutdata, _ = subprocess.Popen(['git', 'describe'],
                                     stdin=subprocess.PIPE,
                                     stdout=subprocess.PIPE).communicate()
    version_git = stdoutdata.rstrip().split('-')[0]
except:
    with open(version_py, 'r') as fh:
        version_git = open(version_py).read().strip().split('=')[-1].replace("'","")

# Write the current version out to version.py to make sure it's up to date
version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep + "__version__='{ver}'".format(ver=version_git))

# Try to get the long description from the README file or the module's
# docstring if the README isn't available.
try:
  README = open(os.path.join(root_dir, 'README.md')).read()
except:
  README = __doc__

setup(
    name='Flask-Fixtures',
    version="{ver}".format(ver=version_git),
    url='http://github.com/flask_fixtures',
    license='Apache License 2.0',
    author='Christopher Roach',
    author_email='vthakr@gmail.com',
    maintainer='Christopher Roach',
    maintainer_email='vthakr@gmail.com',
    description='A fixtures library for testing Flask apps.',
    long_description=README,
    # py_modules=['flask_fixtures'],
    # if you would be using a package instead use packages instead
    # of py_modules:
    packages=['flask_fixtures'],
    zip_safe=False,
    include_package_data=True,
    platforms='any',
    install_requires=[
        'Flask-SQLAlchemy'
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Software Development :: Testing'
    ]
)